name: powershell
version: 'git'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  powershell:
    command: opt/powershell/pwsh
  # powershell:
  #   command: bin/powershell-launch
  # telemetry:
  #   command: bin/powershell-telemetry

parts:
  patches:
    plugin: dump
    source: patches
    prime: [-*]

  scripts:
    plugin: dump
    source: scripts
    prepare: |
      chmod +x powershell-launch powershell-telemetry
    organize:
      '*': bin/

  powershell:
    # after: [scripts]
    # plugin: dump
    # source: https://github.com/PowerShell/PowerShell/releases/download/v6.0.0/powershell_6.0.0-1.ubuntu.16.04_amd64.deb
    after: [scripts, patches]
    plugin: nil
    prepare: |
      curl -L -o powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell-6.0.1-linux-x64.tar.gz
    # patch -Np1 < "$SNAPCRAFT_STAGE/telemetry.diff"
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/powershell
      tar zxf powershell.tar.gz -C $SNAPCRAFT_PART_INSTALL/opt/powershell
      chmod +x $SNAPCRAFT_PART_INSTALL/opt/powershell/pwsh
    stage-packages:
      - libcurl3
      - libicu55
      - liblttng-ust0
      - libssl1.0.0
      - libunwind8
      - libuuid1
      - zlib1g
